/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as SignRouteImport } from './routes/sign'
import { Route as DevFoundationsRouteImport } from './routes/dev/foundations'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as FilesDocumentsIdSourceRouteImport } from './routes/files/documents/$id/source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFoundationsRoute = DevFoundationsRouteImport.update({
  id: '/dev/foundations',
  path: '/dev/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesDocumentsIdSourceRoute = FilesDocumentsIdSourceRouteImport.update({
  id: '/files/documents/$id/source',
  path: '/files/documents/$id/source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/sign': typeof SignRoute
  '/dev/foundations': typeof DevFoundationsRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/files/documents/$id/source': typeof FilesDocumentsIdSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/sign': typeof SignRoute
  '/dev/foundations': typeof DevFoundationsRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/files/documents/$id/source': typeof FilesDocumentsIdSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/sign': typeof SignRoute
  '/dev/foundations': typeof DevFoundationsRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/files/documents/$id/source': typeof FilesDocumentsIdSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prepare'
    | '/sign'
    | '/dev/foundations'
    | '/s/$token'
    | '/api/auth/$'
    | '/files/documents/$id/source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prepare'
    | '/sign'
    | '/dev/foundations'
    | '/s/$token'
    | '/api/auth/$'
    | '/files/documents/$id/source'
  id:
    | '__root__'
    | '/'
    | '/prepare'
    | '/sign'
    | '/dev/foundations'
    | '/s/$token'
    | '/api/auth/$'
    | '/files/documents/$id/source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrepareRoute: typeof PrepareRoute
  SignRoute: typeof SignRoute
  DevFoundationsRoute: typeof DevFoundationsRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  FilesDocumentsIdSourceRoute: typeof FilesDocumentsIdSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/foundations': {
      id: '/dev/foundations'
      path: '/dev/foundations'
      fullPath: '/dev/foundations'
      preLoaderRoute: typeof DevFoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/documents/$id/source': {
      id: '/files/documents/$id/source'
      path: '/files/documents/$id/source'
      fullPath: '/files/documents/$id/source'
      preLoaderRoute: typeof FilesDocumentsIdSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrepareRoute: PrepareRoute,
  SignRoute: SignRoute,
  DevFoundationsRoute: DevFoundationsRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  FilesDocumentsIdSourceRoute: FilesDocumentsIdSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
